on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: [3.8]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install requirements
        run: python -m pip install -r requirements.txt
      - name: Install dev requirements
        run: python -m pip install -r requirements_dev.txt
      - name: patch secret key
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
        run: cat ssrando.py.in | envsubst > ssrando.py
      # - name: Test if the formatting is correct
      #   run: black . --check
      - name: Run tests
        run: python3 -mpytest test/test_placement_file.py
      - name: Install build requirements
        run: python -m pip install -r requirements_build.txt
      - name: Build distribution
        run: pyinstaller ssrando.spec --log-level=WARN
      - name: Make arc-replacements folder
        run: mkdir -p dist/arc-replacements
        shell: bash
      - name: Copy Readme
        run: cp README.md dist
        shell: bash
      - uses: actions/upload-artifact@v2
        with:
          name: dist ${{ matrix.os }}
          path: dist
